networks:
    name: traefik
    external: true
services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    restart: unless-stopped
    environment:
      - WG_HOST=<YOUR_PUBLIC_FQDN>    
      # See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
      - PASSWORD_HASH=<WIREGUARD_BCRYPT_PASSWORD_HASH>
      # Don't push any DNS to clients (= discard default = 1.1.1.1))
      - WG_DEFAULT_DNS=
      - WG_MTU=1420
      - WG_ALLOWED_IPS=<PRIVATE_IP_OF_SERVER>, 10.200.0.1/32
      # - WG_ALLOWED_IPS=192.168.0.XXX/32, 10.200.0.1/32
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      - UI_ENABLE_SORT_CLIENTS=true
    volumes:
      - /home/docker/wireguard/data:/etc/wireguard
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.entrypoints=websecure
      - traefik.http.routers.wireguard.rule=Host(`vpn.<YOUR_DOMAIN>`)
      - traefik.http.routers.wireguard.tls.certresolver=my_http_resolver
      - traefik.http.routers.wireguard.tls=true
      - traefik.http.services.wireguard.loadbalancer.server.port=51821
      - traefik.http.routers.wireguard.middlewares=admin-ipallowlist@file, securityHeaders@file
      - traefik.docker.network=traefik
    networks:
      - traefik
